version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    working_dir: /app
    env_file:
      - ./backend/.env   # Ruta relativa a tu compose
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/reviewsdb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reviewsdb
    ports:
      - "3306:3306"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
