services:
  # FRONTEND REGISTRO
  frontend-registro:
    build:
      context: ./Registro
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - saga-orchestrator

  # FRONTEND LOGIN
  frontend-login:
    build:
      context: ./Login
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - saga-orchestrator

  # SAGA ORCHESTRATOR (nuevo)
  saga-orchestrator:
    build:
      context: ./Servicios/saga-orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - user-service
      - email-service

  # USER SERVICE (registro de usuarios)
  user-service:
    build:
      context: ./Servicios/register-user-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  # EMAIL SERVICE (microservicio de correos)
  email-service:
    build:
      context: ./Servicios/email-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env

  # BASE DE DATOS
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "AJLN", "-d", "User"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:
