# Dockerfile para el backend (Express)
FROM node:20

WORKDIR /app

COPY .env .env
COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npx prisma generate
EXPOSE 3001
CMD ["npm", "start"] 