apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rating
  template:
    metadata:
      labels:
        app: api-rating
    spec:
      containers:
        - name: api-rating
          image: api-rating:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: db-rating
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: ratingdb
            - name: DB_USER
              value: rating
            - name: DB_PASS
              value: ratingpass

---
apiVersion: v1
kind: Service
metadata:
  name: api-rating
spec:
  selector:
    app: api-rating
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
