apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-user
data:
  init.sql: |
    CREATE TABLE users (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );

    INSERT INTO users (name) VALUES ('Alice'), ('Bob');
---
apiVersion: v1
kind: Service
metadata:
  name: db-user
spec:
  selector:
    app: db-user
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-user
  template:
    metadata:
      labels:
        app: db-user
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: userpass
            - name: POSTGRES_DB
              value: userdb
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          emptyDir: {}
        - name: init-script
          configMap:
            name: init-db-user
