apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-user
  template:
    metadata:
      labels:
        app: frontend-user
    spec:
      containers:
        - name: frontend
          image: frontend-login-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-user
spec:
  selector:
    app: frontend-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
