apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-movie
  template:
    metadata:
      labels:
        app: frontend-movie
    spec:
      containers:
        - name: frontend
          image: my-frontend-image:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-movie
spec:
  selector:
    app: frontend-movie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
