apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
        resolver kube-dns.kube-system.svc.cluster.local;

        server {
            listen 80;

            ## User service
            location /login/ {
                proxy_pass http://front-user-login.default.svc.cluster.local;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /register/ {
                proxy_pass http://front-user-register.default.svc.cluster.local;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /saga/ {
                rewrite ^/saga/(.*)$ /$1 break;
                proxy_pass http://api-user-saga.default.svc.cluster.local;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /confirmar {
            proxy_pass http://api-user-saga.default.svc.cluster.local/confirmar;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

            

            # Frontend services
            # location /user/ {
            #     proxy_pass http://frontend-user.default.svc.cluster.local;
            #     proxy_set_header Host $host;
            #     proxy_set_header X-Real-IP $remote_addr;
            # }

            # location /movie/ {
            #     proxy_pass http://frontend-movie.default.svc.cluster.local;
            #     proxy_set_header Host $host;
            #     proxy_set_header X-Real-IP $remote_addr;
            # }

          location /rating/ {
                proxy_pass http://front-rating.default.svc.cluster.local/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Cookie $http_cookie;  # para enviar cookies al backend
            }


            # # API services
            # location /user/api/ {
            #     proxy_pass http://api-user.default.svc.cluster.local;
            #     proxy_set_header Host $host;
            #     proxy_set_header X-Real-IP $remote_addr;
            # }

            # location /movie/api/ {
            #     proxy_pass http://api-movie.default.svc.cluster.local;
            #     proxy_set_header Host $host;
            #     proxy_set_header X-Real-IP $remote_addr;
            # }

            location /rating/api/ {
                proxy_pass http://api-rating.default.svc.cluster.local/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Cookie $http_cookie;
            }

        }
    }
