apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rating
  template:
    metadata:
      labels:
        app: api-rating
    spec:
      containers:
        - name: api-rating
          image: juankarlos1517/api-rating:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: db-rating.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: ratingdb
            - name: DB_USER
              value: rating
            - name: DB_PASS
              value: ratingpass
            - name: AUTH_SERVICE_URL
              value: http://api-saga.default.svc.cluster.local
            - name: DATABASE_URL
              value: postgresql://rating:ratingpass@db-rating:5432/ratingdb

---
apiVersion: v1
kind: Service
metadata:
  name: api-rating
spec:
  selector:
    app: api-rating
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
