apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-rating
  template:
    metadata:
      labels:
        app: front-rating
    spec:
      containers:
        - name: frontend
          image: judajaav/front-rating:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4173

---
apiVersion: v1
kind: Service
metadata:
  name: front-rating
spec:
  selector:
    app: front-rating
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173
  type: ClusterIP
