apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user-login
  template:
    metadata:
      labels:
        app: api-user-login
    spec:
      containers:
        - name: api-user-login
          image: juankarlos1517/api-user-login:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          env:
            - name: JWT_SECRET
              value: 9UhYtozimASoDAKyQUMEtipYhYMEHugOpegaVEPYDOkoFOCEkYtIBEtEteQaLih
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: userpass
            - name: DB_NAME
              value: userdb
            - name: DB_HOST
              value: db-user.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: api-user-login
spec:
  selector:
    app: api-user-login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: ClusterIP
