apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user-email
  template:
    metadata:
      labels:
        app: api-user-email
    spec:
      containers:
        - name: api-user-email
          image: judajaav/api-user-email:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: userpass
            - name: DB_NAME
              value: userdb
            - name: DB_HOST
              value: db-user.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: EMAIL_USER
              value: juankarlos1517@gmail.com
            - name: EMAIL_PASS
              value: nsknftnzmoyogteg
            - name: EMAIL_FROM
              value: juankarlos1517@gmail.com
            - name: FRONTEND_URL
              value: http://localhost:4000/register

---
apiVersion: v1
kind: Service
metadata:
  name: api-user-email
spec:
  selector:
    app: api-user-email
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
