apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-user-login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-user-login
  template:
    metadata:
      labels:
        app: front-user-login
    spec:
      containers:
        - name: frontend
          image: judajaav/front-user-login:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: front-user-login
spec:
  selector:
    app: front-user-login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
