apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-movie
  template:
    metadata:
      labels:
        app: front-movie
    spec:
      containers:
        - name: frontend
          image: judajaav/front-movie
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: front-movie
spec:
  selector:
    app: front-movie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
